version: '3.8'

services:
  rtms:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
#      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db-2
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  db:
    image: "postgres:13.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: password
#    ports:
#      - "8090:8080"
#    depends_on:
#      - db
